// Generated by CoffeeScript 1.6.2
/*
# Fibonacci.js
# Calculate Fibonacci numbers in JavaScript. Ultrafast.
#
# @version 1.2
# @author Lukas Bestle <http://lu-x.me>
# @link https://github.com/vis7mac/fibonaccijs
# @copyright Copyright 2013 Lukas Bestle
# @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
# @file fibonacci.js
*/


(function() {
  var Big, arg, bigjs, count, current2, end, i, last1, last2, output, start, time, _i, _j, _len, _ref;

  count = 1477;

  output = false;

  bigjs = false;

  if (process.argv != null) {
    _ref = process.argv;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      if (arg === '-o') {
        output = true;
      } else if (arg === '-b' && (typeof process !== "undefined" && process !== null)) {
        bigjs = true;
      } else if (!isNaN(arg)) {
        count = arg;
      }
    }
  }

  if (count > 1477 & !bigjs) {
    console.log("The count you requested is to big. Please use Big.js with that (`-b`).");
    return;
  }

  if (bigjs) {
    Big = require('./big');
    last1 = new Big('1');
    last2 = new Big('0');
  } else {
    last1 = 1;
    last2 = 0;
  }

  if (output) {
    console.log("1: " + last2);
    console.log("2: " + last1);
  }

  start = new Date().getTime();

  for (i = _j = 3; 3 <= count ? _j <= count : _j >= count; i = 3 <= count ? ++_j : --_j) {
    current2 = last2;
    last2 = last1;
    if (bigjs) {
      last1 = current2.plus(last1);
    } else {
      last1 = current2 + last1;
    }
    if (output && i < count) {
      console.log("" + i + ": " + last1);
    }
  }

  end = new Date().getTime();

  time = end - start;

  console.log("" + count + ": " + last1);

  console.log("\nCalculating took " + time + " milliseconds. YAY!");

}).call(this);
