// Generated by CoffeeScript 1.6.2
/*
 * Fibonacci.js
 * Calculate Fibonacci numbers in JavaScript. Ultrafast.
 *
 * @version 1.0
 * @author Lukas Bestle <http://lu-x.me>
 * @link https://github.com/vis7mac/fibonaccijs
 * @copyright Copyright 2013 Lukas Bestle
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @file fibonacci.js
*/


(function() {
  var current2, end, i, last1, last2, numbers, start, time, _i;

  start = new Date().getTime();

  last1 = 1;

  last2 = 0;

  console.log("1: " + last2);

  console.log("2: " + last1);

  numbers = process.argv[2] || 1477;

  for (i = _i = 3; 3 <= numbers ? _i <= numbers : _i >= numbers; i = 3 <= numbers ? ++_i : --_i) {
    current2 = last2;
    last2 = last1;
    last1 = current2 + last1;
    console.log("" + i + ": " + last1);
  }

  end = new Date().getTime();

  time = end - start;

  console.log("\nCalculating took " + time + " milliseconds. YAY!");

}).call(this);
